server:
  port: 4004 # Gateway listens on port 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## http://localhost:4005/auth.login
        ## API Gateway --> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        ## REST CLIENT --> http://localhost:4004/api/patients
        ## API GATEWAY --> http://patient-service:8090/api/patients
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: patient-service-route
          uri: http://patient-service:8090
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        ## REST-CLIENT --> http://localhost:8090/api-docs/patients
        ## API-GATEWAY --> http://patient-service:8090/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:8090
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

